== Chapter 2

The only reason Schooner Bailey's wasn't filled to the brim with animals
nearly busting out of its palmwood walls was because it was Sunday
afternoon. For once, the establishment wasn't understaffed, nor did anyone
need to shout in order to be heard even if they were sitting right next to
each other. Bisky and Gardenia were not accustomed to this misleadingly
peaceful setup -- neither of them could remember a time they saw the pub in
daylight -- but, as always, it remained a welcome and familiar spot. And the
food was _amazing_ for a pub in Port Sokuit's Cargo District.

The skunks approached the bar. Their favorite bartender, a gregarious but
perpetually overworked cat named Jem, recognized the skunks from afar. Truth
be told, the only skunks who ever came to Schooner Bailey's in the first
place were Bisky and Gardenia. 

"`Welcome, ladies,`" he announced from behind the bar. Gardenia waved in
that annoying but endearing way Jem came to expect. "`Hey, Jem!`" she
responded. Bisky didn't say anything.

Even though the skunks expected it, they were nevertheless a little
perplexed at how _empty_ the place was. Their game plan typically involved
blending into the boisterous crowd; now, they could gain privacy just by
sitting in a corner.

"`It's Sunday afternoon,`" he shrugged, when he noticed the skunks were
looking around the place as if it was condemned, or had suddenly became
haunted. "`Actually, I don't think I've ever seen you two at this time of
day!`" Bisky smiled, finally. "`Maybe there's time to finally chat?`" Jem
asked.

Gardenia turned to Bisky, and read Bisky's intentions from her face.
"`...Actually, we need some time to ourselves,`" Gardenia said as sweetly as
she could, still facing Bisky.

"`Cool cool cool,`" said Jem. Secretly, he felt relief, knowing he just had
less work to do. "`What can I get ya?`"

"`Frisky Fizz for me,`" Gardenia said.

Bisky consulted the drinks menu, written in chalk on a blackboard behind the
cat.  She quickly located the beer with the highest alcohol content.
"`Seventh Vixen, please. A big one. And a basket of calamari.`"

Jem raised an eyebrow, but punched in the order on the computer anyway.
"`Cool cool cool.`"

"`Yeah, calamari!`" Gardenia accorded.

Jem poured the drinks. Bisky's beer was hilariously larger than Gardenia's
soda pop.  Gardenia paid for it all. The skunks had already agreed to let
this be Gardenia's treat, just this once.

"`Heh, looks like you can have nearly any seat you want,`" Jem said. "`I'll
bring the food out when it's ready.`"

The skunks decided to have a seat outside, in the area that was essentially
a walled garden, but only to the maximum extent that an old, charmingly
dingy pub in the Cargo District could possibly maintain a garden. Some other
animals were already seated on the long benches. It truly was a beautiful
day.
